name: Test and lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install tools
        run: pip install black ruff

      - name: Run Black check
        run: black --check .

      - name: Ruff format
        if: always()
        run: ruff format .

      - name: Ruff fix
        if: always()
        run: ruff check . --fix

      - name: Run Ruff check
        if: always()
        run: ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest